### ISSUE TITLE
Footer text vertical alignment not centered

### ISSUE THREAD

**Issue by ravicodelabs** [datascijedi/website#140]
The footer text vertical alignment seems to have thrown off by a bug on the Quarto side introduced some time after v1.3.298. A temporary fix was implemented to center the footer text vertically. 

Below is the issue filed with Quarto:

https://github.com/quarto-dev/quarto-cli/issues/9938

**Comment by ravicodelabs** [comment]
The Quarto team decided to keep the new behavior (which also has a dependency on Bootstrap) as is (see the above linked issue for details). 

So, closing this and keep our CSS for vertically centering the footer text. 

https://github.com/datascijedi/website/blob/main/css/styles.css:

```css
body .nav-footer {
    align-items: center;
}

body .nav-footer-center {
    min-height: unset;
}
```
